### ISSUE TITLE
0.1.x Release

### ISSUE THREAD

**Issue by JustSoup321** [lowendlibre/hagisk#1]
### TODO
- [ ] Cli options
- [ ] Automatically pull the latest Magisk source
- [ ] Write patches to separate required Magisk files
- [ ] Write patch to modify boot_patch.sh for desktop
- [ ] Write code to wrap around boot_patch.sh environment variables
- [ ] Get sha256sum of patched bootimg to match app-patched bootimg
#### TBD
